# Generated by Django 4.2.20 on 2026-06-13 17:04

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +7XXXXXXXXXX', regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
